osx_image: xcode7.3
language: objective-c
before_install:
- gem install bundler
- bundle install
- bundle exec pod repo add carambastudio https://github.com/carambastudio/Specs
script:
- bundle exec fastlane travis
after_success:
  - bash <(curl -s https://codecov.io/bash)
  # - bash scripts/deploy
